use_frameworks!

platform :ios, '8.0'

target 'KPFoundation_Example' do
  pod 'KPFoundation', :path => '../'

  target 'KPFoundation_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
